### ISSUE TITLE
[Docs]feat: Convert mdx to mdc

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#172]
Currently the docs pages under '/components' were all copied from radix. What we need to do first is we need to convert from the current mdx syntax to [mdc](https://content.nuxtjs.org/guide/writing/mdc/). We have converted the Alert Dialog as an example to be applied to every other components.

### Todos
- [ ] Convert all current component pages to mdc syntax, refer to Alert Dialog page.
- [ ] Some components arent imported from Radix because we just had done it recently, (DropdownMenu, ContextMenu, Menubar...), so add it first then convert it.
- [ ] Review all api/props, examples, make sure everything is correct and working.

**Comment by DennisSmuda** [comment]
This can be closed, I guess right? @khairulhaaziq
