### ISSUE TITLE
[DOCS TRACKER] 1.0

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#206]
This is where we keep track of writing docs progress. If there are any issues/blocker for a specific page, we can add them below their todos list item.

### Overview
- [ ] Introduction
- [ ] Getting Started
- [ ] Accessibility
- [ ] Release

### Guides
- [ ] Styling
- [ ] Animation
- [ ] Composition
- [ ] Server Side Rendering

### Components
- [x] Accordion
- [x] Alert DIalog
- [x] Aspect Ratio
- [x] Avatar
- [ ] Checkbox
    - click function is wrong
- [x] Collapsible
- [ ] Context Menu
- [x] Dialog
- [ ] Dropdown Menu
- [x] Hover Card
- [x] Label
- [ ] Menubar
- [ ] Navigation Menu
- [ ] Popover
- [x] Progress
- [x] Radio Group
- [x] Scroll Area
- [ ] Select
- [x] Separator
- [x] Slider
- [x] Switch
- [x] Tabs
- [x] Toggle
- [x] Toggle Group
- [x] Toolbar
- [x] Tooltip

## General Issues
- [ ] Remove toggle color button
- [ ] Design homepage
- [ ] Add releases on releases page
