### ISSUE TITLE
fix: fix all components that should be controllable and uncontrollable

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#98]
Fix relevant components to be able to be used with or without v-model(controllable or uncontrollable)
Use the useVueModel, refer to #95 
Related to all components with open/close
- [ ] #1  ~wait until built first
- [x] #2 
- [x] #5
- [x] #6 
- [x] #8  
- [x] #9 
- [x] #11 
- [ ] #13 ~wait until built first
- [ ] #14 ~wait until built first
- [x] #15 
- [ ] #17 ~needs refactor to support without v-model first
- [ ] #19 ~wait until built first
- [ ] #21 ~needs refactor to support without v-model first
- [x] #22 #91 
- [ ] #23 ~needs refactor to support without v-model first
- [x] #25 
- [ ] #26 ~needs refactor to support without v-model first
- [x] #28
